In [2]:
import pandas as pd
from datetime import datetime, timedelta

# Veriler
start_date = datetime(2023, 7, 1)
days = 10
dates = [start_date + timedelta(days=i) for i in range(days)]
correct_words = [75, 81, 71, 86, 90, 93, 90, 95, 96, 96]
total_words = 100
accuracy = [correct / total_words * 100 for correct in correct_words]

# DataFrame oluşturma
data = {
    'Tarih': dates,
    'Doğru Okunan Kelimeler': correct_words,
    'Toplam Kelime Sayısı': [total_words] * days,
    'Doğruluk Yüzdesi': accuracy
}

df = pd.DataFrame(data)

# Tarih sütununu uygun formatta gösterme
df['Tarih'] = df['Tarih'].dt.strftime('%Y-%m-%d')

df

        Tarih  Doğru Okunan Kelimeler  Toplam Kelime Sayısı  Doğruluk Yüzdesi
0  2023-07-01                      75                   100              75.0
1  2023-07-02                      81                   100              81.0
2  2023-07-03                      71                   100              71.0
3  2023-07-04                      86                   100              86.0
4  2023-07-05                      90                   100              90.0
5  2023-07-06                      93                   100              93.0
6  2023-07-07                      90                   100              90.0
7  2023-07-08                      95                   100              95.0
8  2023-07-09                      96                   100              96.0
9  2023-07-10                      96                   100              96.0